set_property SRC_FILE_INFO {cfile:C:/Users/willy/Desktop/Paperasse/Job/Celero/IIR/Vivado/IIR/IIR.srcs/constrs_1/imports/src/Basys3.xdc rfile:../../../IIR.srcs/constrs_1/imports/src/Basys3.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W5   IOSTANDARD LVCMOS33 } [get_ports clk]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V17   IOSTANDARD LVCMOS33 } [get_ports rst]
